Repository microsoft/botbuilder-js, pull requests merged in 2018-12, with the labels that each got.

#666 Improve swagger-generation process for bf-connector & bf-schema libraries
  lerna.json
  libraries/botframework-schema/src/index.ts
  libraries/swagger/generateClient.cmd
  libraries/swagger/model_fixes.js
  libraries/swagger/package-lock.json
  libraries/swagger/package.json
Labels: 4.2

#669 add console.error for async TranscriptLogger.logActivity() impl in TranscriptLoggerMiddleware
  libraries/botbuilder-core/src/transcriptLogger.ts
  libraries/botbuilder-core/tests/transcriptMiddleware.test.js
Labels: 4.2

#688 Add AppInsights package into build publish step
  .travis.yml
Labels: 4.2, Approved, P0

#696 delete libraries/README.md
  libraries/README.md
Labels: 4.3
