Repository microsoft/botbuilder-js, pull requests merged in 2019-05, with the labels that each got.

#915 Fix case of imported files for 4.next botbuilder-lg and botbuilder-expression-parser
  libraries/botbuilder-expression-parser/src/expressionEngine.ts
  libraries/botbuilder-expression-parser/src/index.ts
  libraries/botbuilder-lg/src/templateEngine.ts
Labels: 4.5, Adaptive

#918 Feich/decouple lg parser
  libraries/botbuilder-lg/src/LGParser.ts
  libraries/botbuilder-lg/src/index.ts
  libraries/botbuilder-lg/src/lgTemplate.ts
  libraries/botbuilder-lg/src/templateEngine.ts
Labels: Adaptive

#890 [BotFramework-Connector] Fix webpack bundling broken
  libraries/botframework-connector/src/index.ts
Labels: 4.5

#932 Add functions for switchcase statement in LG
  libraries/botbuilder-lg/src/LGFileLexer.g4
  libraries/botbuilder-lg/src/LGFileParser.g4
  libraries/botbuilder-lg/src/analyzer.ts
  libraries/botbuilder-lg/src/evaluator.ts
  libraries/botbuilder-lg/src/expander.ts
  libraries/botbuilder-lg/src/extractor.ts
  libraries/botbuilder-lg/src/generated/LGFileLexer.ts
  libraries/botbuilder-lg/src/generated/LGFileParser.ts
  libraries/botbuilder-lg/src/generated/LGFileParserListener.ts
  libraries/botbuilder-lg/src/generated/LGFileParserVisitor.ts
  libraries/botbuilder-lg/src/staticChecker.ts
  libraries/botbuilder-lg/tests/lg.test.js
  libraries/botbuilder-lg/tests/mslgtool.test.js
  libraries/botbuilder-lg/tests/templateEngineThrowException.test.js
  libraries/botbuilder-lg/tests/testData/examples/Analyzer.lg
  libraries/botbuilder-lg/tests/testData/examples/switchcase.lg
  libraries/botbuilder-lg/tests/testData/exceptionExamples/SwitchCaseFormatError.lg
  libraries/botbuilder-lg/tests/testData/exceptionExamples/SwitchCaseWarning.lg
  libraries/botbuilder-lg/tests/testData/mslgTool/CollateFile3.lg
  libraries/botbuilder-lg/tests/testData/mslgTool/StaticCheckerErrors.lg
  libraries/botbuilder-lg/tests/testData/mslgTool/ValidFile.lg
Labels: Adaptive

#931 [Expression]add more functions
  libraries/botbuilder-expression-parser/tests/badExpression.test.js
  libraries/botbuilder-expression-parser/tests/expression.test.js
  libraries/botbuilder-expression/package.json
  libraries/botbuilder-expression/src/buildInFunction.ts
  libraries/botbuilder-expression/src/expressionType.ts
Labels: Adaptive
