Repository microsoft/botbuilder-js, pull requests merged in 2019-09, with the labels that each got.

#1173 [Parity w/ .NET] Kept tentantId & channelData in CreateConversation
  libraries/botbuilder/src/botFrameworkAdapter.ts
  libraries/botbuilder/tests/botFrameworkAdapter.test.js
Labels: parity with C#

#1168 Update TypeDoc comments for botFrameworkAdapter.ts
  libraries/botbuilder-core/src/botStatePropertyAccessor.ts
  libraries/botbuilder/src/botFrameworkAdapter.ts
Labels: Docs

#1220 [Teams] Add Teams schemas and initial TeamsActivityHandler
  libraries/botbuilder-core/src/activityHandler.ts
  libraries/botbuilder/src/index.ts
  libraries/botbuilder/src/teamsActivityHandler.ts
  libraries/botbuilder/tests/teamsActivityHandler.test.js
  libraries/botframework-schema/src/index.ts
  libraries/botframework-schema/src/teams/extension/index.ts
  libraries/botframework-schema/src/teams/index.ts
Labels: 4.6, teams

#1225 add actionBasedMessagingExtension from samples repo, update .gitignore
  .gitignore
  libraries/botbuilder/tests/teams/actionBasedMessagingExtension/.env
  libraries/botbuilder/tests/teams/actionBasedMessagingExtension/package.json
  libraries/botbuilder/tests/teams/actionBasedMessagingExtension/src/actionBasedMessagingExtensionBot.ts
  libraries/botbuilder/tests/teams/actionBasedMessagingExtension/src/index.ts
  libraries/botbuilder/tests/teams/actionBasedMessagingExtension/teams-app-manifest/icon-color.png
  libraries/botbuilder/tests/teams/actionBasedMessagingExtension/teams-app-manifest/icon-outline.png
  libraries/botbuilder/tests/teams/actionBasedMessagingExtension/teams-app-manifest/manifest.json
  libraries/botbuilder/tests/teams/actionBasedMessagingExtension/tsconfig.json
Labels: 4.6, teams

#1230 adding openApp card action type
  libraries/botframework-schema/src/index.ts
Labels: 4.6, teams
