Repository microsoft/botbuilder-js, pull requests merged in 2019-11, with the labels that each got.

#1392 [Engineering] Remove typescript devDependency from botframework-streaming
  libraries/botframework-streaming/package.json
Labels: bug

#1397 [4.6.1] Manually Cherry-pick #1392 & #1390 to 4.6 branch
  libraries/botbuilder/src/teamsActivityHandler.ts
  libraries/botbuilder/tests/teamsActivityHandler.test.js
  libraries/botframework-streaming/package.json
Labels: 4.6

#1409 [Fix #1404, Transcripts] Fix for TranscriptLoggerMiddleware not checking responses type
  libraries/botbuilder-core/src/transcriptLogger.ts
  libraries/botbuilder-core/tests/transcriptMiddleware.test.js
Labels: 4.6

#1424 [Streaming, Preview] Update 4.6-preview-streaming branch with 4.6.1 release
  .gitignore
  libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts
  libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage/should_correctly_proceed_through_a_waterfall_dialog.json
  libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage/should_create_an_object.json
  libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage/should_delete_an_object.json
  libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage/should_handle_crazy_keys.json
  libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage/should_not_throw_when_deleting_unknown_object.json
  libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage/should_throw_on_invalid_options.json
  libraries/botbuilder-azure/tests/TestData/CosmosDbPartitionedStorage/should_update_an_object.json
  libraries/botbuilder-azure/tests/cosmosDbPartitionedStorage.test.js
  libraries/botbuilder-core/src/transcriptLogger.ts
  libraries/botbuilder-core/tests/transcriptMiddleware.test.js
  libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts
  libraries/botbuilder-dialogs/src/prompts/promptCultureModels.ts
  libraries/botbuilder-dialogs/tests/choicePrompt.test.js
  libraries/botbuilder-dialogs/tests/confirmPrompt.test.js
  libraries/botbuilder/src/teamsActivityHandler.ts
  libraries/botbuilder/tests/teamsActivityHandler.test.js
  libraries/botframework-streaming/package.json
Labels: Streaming Extensions

#1437 [4.6.x] Pin TypeScript devDependency in each library. (Fixes #1436)
  libraries/botbuilder-ai/package.json
  libraries/botbuilder-applicationinsights/package.json
  libraries/botbuilder-azure/package.json
  libraries/botbuilder-core/package.json
  libraries/botbuilder-core/src/skypeMentionNormalizeMiddleware.ts
  libraries/botbuilder-dialogs/package.json
  libraries/botbuilder-testing/package.json
  libraries/botbuilder/package.json
  libraries/botframework-config/package.json
  libraries/botframework-connector/package.json
  libraries/botframework-schema/package.json
  libraries/botframework-streaming/package.json
  package.json
  transcripts/package.json
Labels: P0

#1438 [4.6.x] Fix set-dependency-versions script
  package.json
Labels: 4.6, P0

#1414 [Adaptive] selectors and conditions
  libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onCondition.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onDialogEvent.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onIntent.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onUnknownIntent.ts
  libraries/botbuilder-dialogs-adaptive/src/index.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/conditionalSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/firstSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/index.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/randomSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/trueSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/sequenceContext.ts
  libraries/botbuilder-dialogs-adaptive/src/triggerSelector.ts
  libraries/botbuilder-dialogs-adaptive/tests/conditions.test.js
  libraries/botbuilder-dialogs-declarative/src/factory/typeFactory.ts
  samples/02. textInput/lib/index.js
  samples/02. textInput/lib/index.js.map
  samples/04. onIntent/lib/index.js
  samples/04. onIntent/lib/index.js.map
  samples/04. onIntent/src/index.ts
  samples/05. beginDialog/lib/index.js
  samples/05. beginDialog/lib/index.js.map
  samples/05. beginDialog/src/index.ts
  samples/06. codeAction/lib/index.js
  samples/06. codeAction/lib/index.js.map
  samples/06. codeAction/src/index.ts
  samples/30. stateMachineDialog/src/index.ts
  samples/50. todo-bot/lib/addToDo/index.js
  samples/50. todo-bot/lib/addToDo/index.js.map
  samples/50. todo-bot/lib/deleteToDo/index.js
  samples/50. todo-bot/lib/deleteToDo/index.js.map
  samples/50. todo-bot/lib/rootDialog/index.js
  samples/50. todo-bot/lib/rootDialog/index.js.map
  samples/50. todo-bot/src/addToDo/index.ts
  samples/50. todo-bot/src/deleteToDo/index.ts
  samples/50. todo-bot/src/rootDialog/index.ts
Labels: adaptive

#1442 [R7, Cherry-pick] Cherry-pick TypeScript 3.5.3 pin from 4.6 branch
  libraries/botbuilder-ai/package.json
  libraries/botbuilder-applicationinsights/package.json
  libraries/botbuilder-azure/package.json
  libraries/botbuilder-core/package.json
  libraries/botbuilder-core/src/skypeMentionNormalizeMiddleware.ts
  libraries/botbuilder-dialogs/package.json
  libraries/botbuilder-lg/package.json
  libraries/botbuilder-testing/package.json
  libraries/botbuilder/package.json
  libraries/botframework-config/package.json
  libraries/botframework-connector/package.json
  libraries/botframework-expressions/package.json
  libraries/botframework-schema/package.json
  libraries/botframework-streaming/package.json
  package.json
  transcripts/package.json
Labels: P0, R7
