Repository microsoft/botbuilder-js, pull requests merged in 2020-05, with the labels that each got.

#2198 Add formatNumber, parseEpoch and parseTicks.
  libraries/adaptive-expressions/src/expressionFunctions.ts
  libraries/adaptive-expressions/src/expressionType.ts
  libraries/adaptive-expressions/tests/badExpression.test.js
  libraries/adaptive-expressions/tests/expressionParser.test.js
  libraries/adaptive-expressions/tsconfig.json
Labels: R10

#2218 Update antlr4ts version and add antlr build script
  libraries/adaptive-expressions/.gitignore
  libraries/adaptive-expressions/package.json
  libraries/adaptive-expressions/src/CommonRegex.g4
  libraries/adaptive-expressions/src/generated/CommonRegex.tokens
  libraries/adaptive-expressions/src/generated/CommonRegexLexer.tokens
  libraries/adaptive-expressions/src/generated/CommonRegexLexer.ts
  libraries/adaptive-expressions/src/generated/CommonRegexListener.ts
  libraries/adaptive-expressions/src/generated/CommonRegexParser.ts
  libraries/adaptive-expressions/src/generated/CommonRegexVisitor.ts
  libraries/adaptive-expressions/src/parser/ExpressionAntlrLexer.g4
  libraries/adaptive-expressions/src/parser/ExpressionAntlrParser.g4
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrLexer.tokens
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrLexer.ts
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrParser.tokens
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrParser.ts
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrParserListener.ts
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrParserVisitor.ts
  libraries/botbuilder-lg/.gitignore
  libraries/botbuilder-lg/package.json
  libraries/botbuilder-lg/src/LGFileLexer.g4
  libraries/botbuilder-lg/src/LGFileParser.g4
  libraries/botbuilder-lg/src/LGTemplateLexer.g4
  libraries/botbuilder-lg/src/LGTemplateParser.g4
  libraries/botbuilder-lg/src/generated/LGFileLexer.tokens
  libraries/botbuilder-lg/src/generated/LGFileLexer.ts
  libraries/botbuilder-lg/src/generated/LGFileParser.tokens
  libraries/botbuilder-lg/src/generated/LGFileParser.ts
  libraries/botbuilder-lg/src/generated/LGFileParserListener.ts
  libraries/botbuilder-lg/src/generated/LGFileParserVisitor.ts
  libraries/botbuilder-lg/src/generated/LGTemplateLexer.tokens
  libraries/botbuilder-lg/src/generated/LGTemplateLexer.ts
  libraries/botbuilder-lg/src/generated/LGTemplateParser.tokens
  libraries/botbuilder-lg/src/generated/LGTemplateParser.ts
  libraries/botbuilder-lg/src/generated/LGTemplateParserListener.ts
  libraries/botbuilder-lg/src/generated/LGTemplateParserVisitor.ts
Labels: R10

#2194 Add 'state' to AppBasedLinkQuery (for teams auth flow during link unfurling)
  libraries/botframework-connector/src/teams/models/mappers.ts
  libraries/botframework-schema/etc/botframework-schema.api.md
  libraries/botframework-schema/src/teams/index.ts
Labels: R10

#2220 [Expression] fix coalesce bug
  libraries/adaptive-expressions/src/expressionFunctions.ts
  libraries/adaptive-expressions/tests/expressionParser.test.js
Labels: R10

#2217 Allow loading settings from turn state
  libraries/botbuilder-dialogs/src/memory/scopes/settingsMemoryScope.ts
  libraries/botbuilder-dialogs/tests/memory_memoryScopes.test.js
  libraries/botbuilder-dialogs/tests/test.settings.json
Labels: R10

#2255 [PORT]Make template name format consistent with function name format
  libraries/botbuilder-lg/src/templateErrors.ts
  libraries/botbuilder-lg/src/templatesParser.ts
  libraries/botbuilder-lg/tests/lgDiagnostic.test.js
  libraries/botbuilder-lg/tests/testData/exceptionExamples/ErrorTemplateName.lg
Labels: R10

#2268 replace atob package to be compatible with web worker
  libraries/adaptive-expressions/package.json
  libraries/adaptive-expressions/src/expressionFunctions.ts
Labels: lg

#2223 Remove node exports from utilities
  libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts
  libraries/botframework-streaming/src/utilities/index.ts
Labels: BF:Patch:4.9, R9, blocked
