Repository microsoft/botbuilder-js, pull requests merged in 2020-10, with the labels that each got.

#2789 SwitchCondition with number throws an exception when compared against a string
  libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_Switch.test.dialog
  libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_Switch_Bool.test.dialog
  libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_Switch_Number.test.dialog
  libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/SwitchBool.dialog
  libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/SwitchNumber.dialog
  libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/SwitchString.dialog
  libraries/botbuilder-dialogs-adaptive/src/actions/case.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/switchCondition.ts
Labels: Area: Adaptive

#2792 [PORT]Support several question mark operators in Expression
  libraries/adaptive-expressions/src/expressionFunctions.ts
  libraries/adaptive-expressions/src/parser/ExpressionAntlrLexer.g4
  libraries/adaptive-expressions/src/parser/ExpressionAntlrParser.g4
  libraries/adaptive-expressions/src/parser/expressionParser.ts
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrLexer.tokens
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrLexer.ts
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrParser.tokens
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrParser.ts
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrParserListener.ts
  libraries/adaptive-expressions/src/parser/generated/ExpressionAntlrParserVisitor.ts
  libraries/adaptive-expressions/tests/expressionParser.test.js
Labels: Porting

#2794 [PORT]Support null/undefined result in LG output
  libraries/adaptive-expressions/src/builtinFunctions/formatNumber.ts
  libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts
  libraries/adaptive-expressions/tests/expressionProperty.test.ts
  libraries/botbuilder-lg/src/evaluator.ts
  libraries/botbuilder-lg/src/expander.ts
  libraries/botbuilder-lg/tests/lg.test.js
  libraries/botbuilder-lg/tests/testData/examples/NullTolerant.lg
Labels: Porting

#2793 TriggerTree and MostSpecificSelector
  libraries/adaptive-expressions/src/builtinFunctions/ignore.ts
  libraries/adaptive-expressions/src/builtinFunctions/optional.ts
  libraries/adaptive-expressions/src/expression.ts
  libraries/adaptive-expressions/src/expressionEvaluator.ts
  libraries/adaptive-expressions/src/expressionFunctions.ts
  libraries/adaptive-expressions/src/index.ts
  libraries/adaptive-expressions/src/triggerTrees/clause.ts
  libraries/adaptive-expressions/src/triggerTrees/index.ts
  libraries/adaptive-expressions/src/triggerTrees/node.ts
  libraries/adaptive-expressions/src/triggerTrees/optimizer.ts
  libraries/adaptive-expressions/src/triggerTrees/quantifier.ts
  libraries/adaptive-expressions/src/triggerTrees/relationshipType.ts
  libraries/adaptive-expressions/src/triggerTrees/trigger.ts
  libraries/adaptive-expressions/src/triggerTrees/triggerTree.ts
  libraries/adaptive-expressions/tests/triggerTree.test.js
  libraries/botbuilder-dialogs-adaptive-testing/tests/selector.test.js
  libraries/botbuilder-dialogs-adaptive/src/actions/dynamicBeginDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/adaptiveDialogComponentRegistration.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/conditionalSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/firstSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/index.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/mostSpecificSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/randomSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/selectors/trueSelector.ts
  libraries/botbuilder-dialogs-adaptive/src/triggerSelector.ts
Labels: Area: Adaptive, Area: Adaptive expression

#2870 Renamed JoinOperator to joinOperator
  libraries/botbuilder-ai/src/qnaMakerDialog.ts
  libraries/botbuilder-ai/src/qnamaker-interfaces/joinOperator.ts
Labels: Area: AI-QnAMaker

#2771 Allow interrruptions in BeginSkill
  libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts
  libraries/botbuilder-dialogs-adaptive/src/adaptiveDialogComponentRegistration.ts
  libraries/botbuilder-dialogs-adaptive/tests/beginSkill.test.js
Labels: Area: Adaptive

#2504 Added useBotState()
  libraries/botbuilder-core/src/adapterExtensions.ts
  libraries/botbuilder-core/src/index.ts
  libraries/botbuilder-core/src/registerClassMiddleware.ts
  libraries/botbuilder-dialogs-adaptive-testing/src/testScript.ts
Labels: blocked

#2838 [#2602] [JSDoc] Add missing documentation for botbuilder-applicationinsights files
  libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts
Labels: Area: Docs

#2841 [#2602] [JSDoc] Add missing documentation for teams-scenarios files
  libraries/teams-scenarios/conversationUpdate/src/conversationUpdateBot.ts
  libraries/teams-scenarios/fileUpload/src/fileUploadBot.ts
  libraries/teams-scenarios/link-unfurling/src/linkUnfurling.ts
  libraries/teams-scenarios/mentionsBot/src/mentionsBot.ts
  libraries/teams-scenarios/messageReaction/src/activityLog.ts
  libraries/teams-scenarios/messageReaction/src/messageReactionBot.ts
  libraries/teams-scenarios/messagingExtensionAuth/src/messagingExtensionAuthBot.ts
  libraries/teams-scenarios/messagingExtensionConfig/src/messagingExtensionConfigBot.ts
  libraries/teams-scenarios/notificationOnly/src/notificationOnlyBot.ts
  libraries/teams-scenarios/office365Card/src/office365CardsBot.ts
  libraries/teams-scenarios/replyToChannel/src/replyToChannelBot.ts
  libraries/teams-scenarios/roster/src/rosterBot.ts
  libraries/teams-scenarios/roster/src/teamsTenantFilteringMiddleware.ts
  libraries/teams-scenarios/searchBasedMessagingExtension/src/teamsSearchExtensionBot.ts
  libraries/teams-scenarios/taskModule/src/taskModuleBot.ts
Labels: Area: Docs

#2839 [#2602] [JSDoc] Add missing documentation for teams-scenarios root
  libraries/teams-scenarios/actionBasedMessagingExtension-fetchTask/src/actionBasedMessagingExtensionFetchBot.ts
  libraries/teams-scenarios/actionBasedMessagingExtension-fetchTask/src/adaptiveCardHelper.ts
  libraries/teams-scenarios/actionBasedMessagingExtension-fetchTask/src/cardResponseHelpers.ts
  libraries/teams-scenarios/actionBasedMessagingExtension-fetchTask/src/submitExampleData.ts
  libraries/teams-scenarios/actionBasedMessagingExtension/src/actionBasedMessagingExtensionBot.ts
  libraries/teams-scenarios/activityUpdateAndDelete/src/activityUpdateAndDeleteBot.ts
  libraries/teams-scenarios/adaptiveCards/src/adaptiveCardsBot.ts
  libraries/teams-scenarios/cardBotFramework/src/cardsBot.ts
  libraries/teams-scenarios/integrationBot/src/activityLog.ts
  libraries/teams-scenarios/integrationBot/src/adaptiveCardHelper.ts
  libraries/teams-scenarios/integrationBot/src/cardResponseHelpers.ts
  libraries/teams-scenarios/integrationBot/src/integrationBot.ts
  libraries/teams-scenarios/integrationBot/src/submitExampleData.ts
  libraries/teams-scenarios/integrationBot/src/teamsTenantFilteringMiddleware.ts
Labels: Area: Docs

#2855 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/expressionProperties
  libraries/adaptive-expressions/src/expressionProperties/arrayExpression.ts
  libraries/adaptive-expressions/src/expressionProperties/boolExpression.ts
  libraries/adaptive-expressions/src/expressionProperties/enumExpression.ts
  libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts
  libraries/adaptive-expressions/src/expressionProperties/intExpression.ts
  libraries/adaptive-expressions/src/expressionProperties/numberExpression.ts
  libraries/adaptive-expressions/src/expressionProperties/objectExpression.ts
  libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts
  libraries/adaptive-expressions/src/expressionProperties/valueExpression.ts
Labels: Area: Docs

#2851 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 10/10
  libraries/adaptive-expressions/src/builtinFunctions/unique.ts
  libraries/adaptive-expressions/src/builtinFunctions/uriComponent.ts
  libraries/adaptive-expressions/src/builtinFunctions/uriComponentToString.ts
  libraries/adaptive-expressions/src/builtinFunctions/uriHost.ts
  libraries/adaptive-expressions/src/builtinFunctions/uriPath.ts
  libraries/adaptive-expressions/src/builtinFunctions/uriPathAndQuery.ts
  libraries/adaptive-expressions/src/builtinFunctions/uriPort.ts
  libraries/adaptive-expressions/src/builtinFunctions/uriQuery.ts
  libraries/adaptive-expressions/src/builtinFunctions/uriScheme.ts
  libraries/adaptive-expressions/src/builtinFunctions/utcNow.ts
  libraries/adaptive-expressions/src/builtinFunctions/where.ts
  libraries/adaptive-expressions/src/builtinFunctions/year.ts
Labels: Area: Docs

#2850 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 9/10
  libraries/adaptive-expressions/src/builtinFunctions/substring.ts
  libraries/adaptive-expressions/src/builtinFunctions/subtract.ts
  libraries/adaptive-expressions/src/builtinFunctions/subtractFromTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/sum.ts
  libraries/adaptive-expressions/src/builtinFunctions/take.ts
  libraries/adaptive-expressions/src/builtinFunctions/ticks.ts
  libraries/adaptive-expressions/src/builtinFunctions/ticksToDays.ts
  libraries/adaptive-expressions/src/builtinFunctions/ticksToHours.ts
  libraries/adaptive-expressions/src/builtinFunctions/ticksToMinutes.ts
  libraries/adaptive-expressions/src/builtinFunctions/timeTransformEvaluator.ts
  libraries/adaptive-expressions/src/builtinFunctions/titleCase.ts
  libraries/adaptive-expressions/src/builtinFunctions/toLower.ts
  libraries/adaptive-expressions/src/builtinFunctions/toUpper.ts
  libraries/adaptive-expressions/src/builtinFunctions/trim.ts
  libraries/adaptive-expressions/src/builtinFunctions/union.ts
Labels: Area: Docs

#2849 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 8/10
  libraries/adaptive-expressions/src/builtinFunctions/select.ts
  libraries/adaptive-expressions/src/builtinFunctions/sentenceCase.ts
  libraries/adaptive-expressions/src/builtinFunctions/setPathToValue.ts
  libraries/adaptive-expressions/src/builtinFunctions/setProperty.ts
  libraries/adaptive-expressions/src/builtinFunctions/skip.ts
  libraries/adaptive-expressions/src/builtinFunctions/sortBy.ts
  libraries/adaptive-expressions/src/builtinFunctions/sortByDescending.ts
  libraries/adaptive-expressions/src/builtinFunctions/split.ts
  libraries/adaptive-expressions/src/builtinFunctions/startOfDay.ts
  libraries/adaptive-expressions/src/builtinFunctions/startOfHour.ts
  libraries/adaptive-expressions/src/builtinFunctions/startOfMonth.ts
  libraries/adaptive-expressions/src/builtinFunctions/startsWith.ts
  libraries/adaptive-expressions/src/builtinFunctions/string.ts
  libraries/adaptive-expressions/src/builtinFunctions/stringTransformEvaluator.ts
  libraries/adaptive-expressions/src/builtinFunctions/subArray.ts
Labels: Area: Docs

#2848 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 7/10
  libraries/adaptive-expressions/src/builtinFunctions/multivariateNumericEvaluator.ts
  libraries/adaptive-expressions/src/builtinFunctions/newGuid.ts
  libraries/adaptive-expressions/src/builtinFunctions/not.ts
  libraries/adaptive-expressions/src/builtinFunctions/notEqual.ts
  libraries/adaptive-expressions/src/builtinFunctions/numberTransformEvaluator.ts
  libraries/adaptive-expressions/src/builtinFunctions/numericEvaluator.ts
  libraries/adaptive-expressions/src/builtinFunctions/optional.ts
  libraries/adaptive-expressions/src/builtinFunctions/or.ts
  libraries/adaptive-expressions/src/builtinFunctions/power.ts
  libraries/adaptive-expressions/src/builtinFunctions/rand.ts
  libraries/adaptive-expressions/src/builtinFunctions/range.ts
  libraries/adaptive-expressions/src/builtinFunctions/removeProperty.ts
  libraries/adaptive-expressions/src/builtinFunctions/replace.ts
  libraries/adaptive-expressions/src/builtinFunctions/replaceIgnoreCase.ts
  libraries/adaptive-expressions/src/builtinFunctions/round.ts
Labels: Area: Docs

#2847 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 6/10
  libraries/adaptive-expressions/src/builtinFunctions/jPath.ts
  libraries/adaptive-expressions/src/builtinFunctions/join.ts
  libraries/adaptive-expressions/src/builtinFunctions/json.ts
  libraries/adaptive-expressions/src/builtinFunctions/jsonStringify.ts
  libraries/adaptive-expressions/src/builtinFunctions/last.ts
  libraries/adaptive-expressions/src/builtinFunctions/lastIndexOf.ts
  libraries/adaptive-expressions/src/builtinFunctions/length.ts
  libraries/adaptive-expressions/src/builtinFunctions/lessThan.ts
  libraries/adaptive-expressions/src/builtinFunctions/lessThanOrEqual.ts
  libraries/adaptive-expressions/src/builtinFunctions/max.ts
  libraries/adaptive-expressions/src/builtinFunctions/merge.ts
  libraries/adaptive-expressions/src/builtinFunctions/min.ts
  libraries/adaptive-expressions/src/builtinFunctions/mod.ts
  libraries/adaptive-expressions/src/builtinFunctions/month.ts
  libraries/adaptive-expressions/src/builtinFunctions/multiply.ts
Labels: Area: Docs

#2846 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 5/10
  libraries/adaptive-expressions/src/builtinFunctions/indexOf.ts
  libraries/adaptive-expressions/src/builtinFunctions/indicesAndValues.ts
  libraries/adaptive-expressions/src/builtinFunctions/int.ts
  libraries/adaptive-expressions/src/builtinFunctions/intersection.ts
  libraries/adaptive-expressions/src/builtinFunctions/isArray.ts
  libraries/adaptive-expressions/src/builtinFunctions/isBoolean.ts
  libraries/adaptive-expressions/src/builtinFunctions/isDate.ts
  libraries/adaptive-expressions/src/builtinFunctions/isDateRange.ts
  libraries/adaptive-expressions/src/builtinFunctions/isDateTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/isDefinite.ts
  libraries/adaptive-expressions/src/builtinFunctions/isDuration.ts
  libraries/adaptive-expressions/src/builtinFunctions/isFloat.ts
  libraries/adaptive-expressions/src/builtinFunctions/isInteger.ts
  libraries/adaptive-expressions/src/builtinFunctions/isMatch.ts
  libraries/adaptive-expressions/src/builtinFunctions/isObject.ts
  libraries/adaptive-expressions/src/builtinFunctions/isPresent.ts
  libraries/adaptive-expressions/src/builtinFunctions/isString.ts
  libraries/adaptive-expressions/src/builtinFunctions/isTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/isTimeRange.ts
Labels: Area: Docs

#2845 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 4/10
  libraries/adaptive-expressions/src/builtinFunctions/formatDateTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/formatEpoch.ts
  libraries/adaptive-expressions/src/builtinFunctions/formatNumber.ts
  libraries/adaptive-expressions/src/builtinFunctions/formatTicks.ts
  libraries/adaptive-expressions/src/builtinFunctions/getFutureTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/getNextViableDate.ts
  libraries/adaptive-expressions/src/builtinFunctions/getNextViableTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/getPastTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/getPreviousViableDate.ts
  libraries/adaptive-expressions/src/builtinFunctions/getPreviousViableTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/getProperty.ts
  libraries/adaptive-expressions/src/builtinFunctions/getTimeOfDay.ts
  libraries/adaptive-expressions/src/builtinFunctions/greaterThan.ts
  libraries/adaptive-expressions/src/builtinFunctions/greaterThanOrEqual.ts
  libraries/adaptive-expressions/src/builtinFunctions/if.ts
  libraries/adaptive-expressions/src/builtinFunctions/ignore.ts
Labels: Area: Docs

#2844 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 3/10
  libraries/adaptive-expressions/src/builtinFunctions/divide.ts
  libraries/adaptive-expressions/src/builtinFunctions/element.ts
  libraries/adaptive-expressions/src/builtinFunctions/empty.ts
  libraries/adaptive-expressions/src/builtinFunctions/endsWith.ts
  libraries/adaptive-expressions/src/builtinFunctions/equal.ts
  libraries/adaptive-expressions/src/builtinFunctions/exists.ts
  libraries/adaptive-expressions/src/builtinFunctions/first.ts
  libraries/adaptive-expressions/src/builtinFunctions/flatten.ts
  libraries/adaptive-expressions/src/builtinFunctions/float.ts
  libraries/adaptive-expressions/src/builtinFunctions/floor.ts
  libraries/adaptive-expressions/src/builtinFunctions/foreach.ts
Labels: Area: Docs

#2816 [#2602] [JSDoc] Add missing documentation for botbuilder-ai
  libraries/botbuilder-ai/src/globals.ts
  libraries/botbuilder-ai/src/luisRecognizer.ts
  libraries/botbuilder-ai/src/luisRecognizerOptions.ts
  libraries/botbuilder-ai/src/luisRecognizerOptionsV2.ts
  libraries/botbuilder-ai/src/luisRecognizerOptionsV3.ts
  libraries/botbuilder-ai/src/qnaMaker.ts
  libraries/botbuilder-ai/src/qnamaker-utils/activeLearningUtils.ts
  libraries/botbuilder-ai/src/qnamaker-utils/generateAnswerUtils.ts
  libraries/botbuilder-ai/src/qnamaker-utils/httpRequestUtils.ts
  libraries/botbuilder-ai/src/qnamaker-utils/trainUtils.ts
Labels: Area: Docs

#2843 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 1/10
  libraries/adaptive-expressions/src/builtinFunctions/accessor.ts
  libraries/adaptive-expressions/src/builtinFunctions/add.ts
  libraries/adaptive-expressions/src/builtinFunctions/addDays.ts
  libraries/adaptive-expressions/src/builtinFunctions/addHours.ts
  libraries/adaptive-expressions/src/builtinFunctions/addMinutes.ts
  libraries/adaptive-expressions/src/builtinFunctions/addOrdinal.ts
  libraries/adaptive-expressions/src/builtinFunctions/addProperty.ts
  libraries/adaptive-expressions/src/builtinFunctions/addSeconds.ts
  libraries/adaptive-expressions/src/builtinFunctions/addToTime.ts
  libraries/adaptive-expressions/src/builtinFunctions/and.ts
  libraries/adaptive-expressions/src/builtinFunctions/average.ts
  libraries/adaptive-expressions/src/builtinFunctions/base64.ts
  libraries/adaptive-expressions/src/builtinFunctions/base64ToBinary.ts
  libraries/adaptive-expressions/src/builtinFunctions/base64ToString.ts
  libraries/adaptive-expressions/src/builtinFunctions/binary.ts
  libraries/adaptive-expressions/src/builtinFunctions/bool.ts
Labels: Area: Docs

#2817 [#2602] [JSDoc] Add missing documentation for botbuilder-azure
  libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts
  libraries/botbuilder-azure/src/blobStorage.ts
  libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts
  libraries/botbuilder-azure/src/cosmosDbStorage.ts
  libraries/botbuilder-azure/src/doOnce.ts
Labels: Area: Docs

#2829 [#2602] [JSDoc] Add missing documentation for botframework-config
  libraries/botframework-config/src/botConfiguration.ts
  libraries/botframework-config/src/botRecipe.ts
  libraries/botframework-config/src/models/appInsightsService.ts
  libraries/botframework-config/src/models/blobStorageService.ts
  libraries/botframework-config/src/models/botService.ts
  libraries/botframework-config/src/models/cosmosDbService.ts
  libraries/botframework-config/src/models/endpointService.ts
  libraries/botframework-config/src/models/fileService.ts
  libraries/botframework-config/src/models/genericService.ts
  libraries/botframework-config/src/models/luisService.ts
  libraries/botframework-config/src/models/qnaMakerService.ts
Labels: Area: Docs

#2852 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs-adaptive root
  libraries/botbuilder-dialogs-adaptive/src/actionContext.ts
  libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/adaptiveEvents.ts
  libraries/botbuilder-dialogs-adaptive/src/entityAssignments.ts
  libraries/botbuilder-dialogs-adaptive/src/entityInfo.ts
  libraries/botbuilder-dialogs-adaptive/src/jsonExtensions.ts
  libraries/botbuilder-dialogs-adaptive/src/languagePolicy.ts
  libraries/botbuilder-dialogs-adaptive/src/languageResourceLoader.ts
  libraries/botbuilder-dialogs-adaptive/src/propertySchema.ts
  libraries/botbuilder-dialogs-adaptive/src/schemaHelper.ts
Labels: Area: Docs

#2828 [#2602] [JSDoc] Add missing documentation for botbuilder-lg root files
  libraries/botbuilder-lg/src/analyzer.ts
  libraries/botbuilder-lg/src/analyzerResult.ts
  libraries/botbuilder-lg/src/customizedMemory.ts
  libraries/botbuilder-lg/src/diagnostic.ts
  libraries/botbuilder-lg/src/errorListener.ts
  libraries/botbuilder-lg/src/evaluationOptions.ts
  libraries/botbuilder-lg/src/evaluationTarget.ts
  libraries/botbuilder-lg/src/evaluator.ts
  libraries/botbuilder-lg/src/expander.ts
  libraries/botbuilder-lg/src/extractor.ts
  libraries/botbuilder-lg/src/lgResource.ts
  libraries/botbuilder-lg/src/multiLanguageLG.ts
Labels: Area: Docs

#2822 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs/memory/scopes
  libraries/botbuilder-dialogs/src/memory/scopes/botStateMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/classMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/conversationMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/dialogClassMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/dialogMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/memoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/settingsMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/thisMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/turnMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/userMemoryScope.ts
Labels: Area: Docs

#2827 [#2602] [JSDoc] Add missing documentation for botframework-connector
  libraries/botframework-connector/src/auth/appCredentials.ts
  libraries/botframework-connector/src/auth/authenticationConfiguration.ts
  libraries/botframework-connector/src/auth/authenticationError.ts
  libraries/botframework-connector/src/auth/certificateAppCredentials.ts
  libraries/botframework-connector/src/auth/claimsIdentity.ts
  libraries/botframework-connector/src/auth/credentialProvider.ts
  libraries/botframework-connector/src/auth/jwtTokenExtractor.ts
  libraries/botframework-connector/src/auth/microsoftAppCredentials.ts
  libraries/botframework-connector/src/auth/openIdMetadata.ts
  libraries/botframework-connector/src/emulatorApiClient.ts
  libraries/botframework-connector/src/teams/operations/teams.ts
  libraries/botframework-connector/src/teams/teamsConnectorClientContext.ts
Labels: Area: Docs

#2826 [#2602] [JSDoc] Add missing documentation for botframework-streaming
  libraries/botframework-streaming/src/assemblers/payloadAssembler.ts
  libraries/botframework-streaming/src/contentStream.ts
  libraries/botframework-streaming/src/disassemblers/cancelDisassembler.ts
  libraries/botframework-streaming/src/disassemblers/httpContentStreamDisassembler.ts
  libraries/botframework-streaming/src/disassemblers/payloadDisassembler.ts
  libraries/botframework-streaming/src/disassemblers/requestDisassembler.ts
  libraries/botframework-streaming/src/disassemblers/responseDisassembler.ts
  libraries/botframework-streaming/src/httpContentStream.ts
  libraries/botframework-streaming/src/namedPipe/namedPipeClient.ts
  libraries/botframework-streaming/src/namedPipe/namedPipeServer.ts
  libraries/botframework-streaming/src/namedPipe/namedPipeTransport.ts
  libraries/botframework-streaming/src/protocolAdapter.ts
  libraries/botframework-streaming/src/streamingRequest.ts
  libraries/botframework-streaming/src/streamingResponse.ts
  libraries/botframework-streaming/src/subscribableStream.ts
  libraries/botframework-streaming/src/utilities/protocol-base.ts
Labels: Area: Docs

#2823 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs/memory/pathResolver
  libraries/botbuilder-dialogs/src/memory/pathResolvers/aliasPathResolver.ts
  libraries/botbuilder-dialogs/src/memory/pathResolvers/atAtPathResolver.ts
  libraries/botbuilder-dialogs/src/memory/pathResolvers/atPathResolver.ts
  libraries/botbuilder-dialogs/src/memory/pathResolvers/dollarPathResolver.ts
  libraries/botbuilder-dialogs/src/memory/pathResolvers/hashPathResolver.ts
  libraries/botbuilder-dialogs/src/memory/pathResolvers/percentPathResolver.ts
Labels: Area: Docs

#2824 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs/memory
  libraries/botbuilder-dialogs/src/memory/dialogPath.ts
  libraries/botbuilder-dialogs/src/memory/dialogStateManager.ts
  libraries/botbuilder-dialogs/src/memory/scopePath.ts
  libraries/botbuilder-dialogs/src/memory/thisPath.ts
  libraries/botbuilder-dialogs/src/memory/turnPath.ts
Labels: Area: Docs

#2821 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs/choices & /prompts
  libraries/botbuilder-dialogs/src/choices/choiceFactory.ts
  libraries/botbuilder-dialogs/src/prompts/activityPrompt.ts
  libraries/botbuilder-dialogs/src/prompts/attachmentPrompt.ts
  libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts
  libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts
  libraries/botbuilder-dialogs/src/prompts/datetimePrompt.ts
  libraries/botbuilder-dialogs/src/prompts/numberPrompt.ts
  libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts
  libraries/botbuilder-dialogs/src/prompts/prompt.ts
  libraries/botbuilder-dialogs/src/prompts/promptCultureModels.ts
  libraries/botbuilder-dialogs/src/prompts/textPrompt.ts
Labels: Area: Docs

#2820 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs/Root
  libraries/botbuilder-dialogs/src/componentDialog.ts
  libraries/botbuilder-dialogs/src/dialog.ts
  libraries/botbuilder-dialogs/src/dialogContainer.ts
  libraries/botbuilder-dialogs/src/dialogContext.ts
  libraries/botbuilder-dialogs/src/dialogEvents.ts
  libraries/botbuilder-dialogs/src/dialogHelper.ts
  libraries/botbuilder-dialogs/src/dialogManager.ts
  libraries/botbuilder-dialogs/src/dialogTurnStateConstants.ts
  libraries/botbuilder-dialogs/src/skillDialog.ts
  libraries/botbuilder-dialogs/src/waterfallDialog.ts
Labels: Area: Docs

#2856 [#2602] [JSDoc] Add missing documentation for adaptive-expressions root files
  libraries/adaptive-expressions/src/commonRegex.ts
  libraries/adaptive-expressions/src/constant.ts
  libraries/adaptive-expressions/src/expression.ts
  libraries/adaptive-expressions/src/expressionFunctions.ts
  libraries/adaptive-expressions/src/functionTable.ts
  libraries/adaptive-expressions/src/functionUtils.ts
  libraries/adaptive-expressions/src/memory/simpleObjectMemory.ts
  libraries/adaptive-expressions/src/memory/stackedMemory.ts
  libraries/adaptive-expressions/src/options.ts
  libraries/adaptive-expressions/src/parser/expressionParser.ts
  libraries/adaptive-expressions/src/parser/parseErrorListener.ts
  libraries/adaptive-expressions/src/regexErrorListener.ts
  libraries/adaptive-expressions/src/timeZoneConverter.ts
Labels: Area: Docs

#2832 [#2602] [JSDoc] Add missing documentation for botbuilder-core files
  libraries/botbuilder-core/src/activityFactory.ts
  libraries/botbuilder-core/src/activityHandler.ts
  libraries/botbuilder-core/src/autoSaveStateMiddleware.ts
  libraries/botbuilder-core/src/botAdapter.ts
  libraries/botbuilder-core/src/botStatePropertyAccessor.ts
  libraries/botbuilder-core/src/botTelemetryClient.ts
  libraries/botbuilder-core/src/browserStorage.ts
  libraries/botbuilder-core/src/cardFactory.ts
  libraries/botbuilder-core/src/memoryStorage.ts
  libraries/botbuilder-core/src/middlewareSet.ts
  libraries/botbuilder-core/src/showTypingMiddleware.ts
  libraries/botbuilder-core/src/skypeMentionNormalizeMiddleware.ts
  libraries/botbuilder-core/src/stringUtils.ts
  libraries/botbuilder-core/src/telemetryLoggerMiddleware.ts
  libraries/botbuilder-core/src/testAdapter.ts
  libraries/botbuilder-core/src/turnContext.ts
  libraries/botbuilder-core/src/turnContextStateCollection.ts
Labels: Area: Docs

#2837 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs-declarative files
  libraries/botbuilder-dialogs-declarative/src/pathUtil.ts
  libraries/botbuilder-dialogs-declarative/src/resources/folderResourceProvider.ts
  libraries/botbuilder-dialogs-declarative/src/resources/resourceProvider.ts
Labels: Area: Docs

#2842 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 2/10
  libraries/adaptive-expressions/src/builtinFunctions/ceiling.ts
  libraries/adaptive-expressions/src/builtinFunctions/coalesce.ts
  libraries/adaptive-expressions/src/builtinFunctions/comparisonEvaluator.ts
  libraries/adaptive-expressions/src/builtinFunctions/concat.ts
  libraries/adaptive-expressions/src/builtinFunctions/contains.ts
  libraries/adaptive-expressions/src/builtinFunctions/convertFromUTC.ts
  libraries/adaptive-expressions/src/builtinFunctions/convertToUTC.ts
  libraries/adaptive-expressions/src/builtinFunctions/count.ts
  libraries/adaptive-expressions/src/builtinFunctions/countWord.ts
  libraries/adaptive-expressions/src/builtinFunctions/createArray.ts
  libraries/adaptive-expressions/src/builtinFunctions/dataUri.ts
  libraries/adaptive-expressions/src/builtinFunctions/dataUriToBinary.ts
  libraries/adaptive-expressions/src/builtinFunctions/dataUriToString.ts
  libraries/adaptive-expressions/src/builtinFunctions/dateFunc.ts
  libraries/adaptive-expressions/src/builtinFunctions/dateReadBack.ts
  libraries/adaptive-expressions/src/builtinFunctions/dateTimeDiff.ts
  libraries/adaptive-expressions/src/builtinFunctions/dayOfMonth.ts
  libraries/adaptive-expressions/src/builtinFunctions/dayOfWeek.ts
  libraries/adaptive-expressions/src/builtinFunctions/dayOfYear.ts
  libraries/botbuilder-dialogs/src/memory/scopes/botStateMemoryScope.ts
Labels: Area: Docs

#2854 [#2602] [JSDoc] Add missing documentation for adaptive-expressions/converters
  libraries/adaptive-expressions/src/converters/arrayExpressionConverter.ts
  libraries/adaptive-expressions/src/converters/boolExpressionConverter.ts
  libraries/adaptive-expressions/src/converters/enumExpressionConverter.ts
  libraries/adaptive-expressions/src/converters/expressionConverter.ts
  libraries/adaptive-expressions/src/converters/intExpressionConverter.ts
  libraries/adaptive-expressions/src/converters/numberExpressionConverter.ts
  libraries/adaptive-expressions/src/converters/objectExpressionConverter.ts
  libraries/adaptive-expressions/src/converters/stringExpressionConveter.ts
  libraries/adaptive-expressions/src/converters/valueExpressionConverter.ts
Labels: Area: Docs

#2825 [#2602] [JSDoc] Add missing documentation for botframework-streaming websocket and payloads folders
  libraries/botframework-streaming/src/payloadTransport/payloadReceiver.ts
  libraries/botframework-streaming/src/payloadTransport/payloadSender.ts
  libraries/botframework-streaming/src/payloadTransport/transportDisconnectedEvent.ts
  libraries/botframework-streaming/src/payloads/headerSerializer.ts
  libraries/botframework-streaming/src/payloads/payloadAssemblerManager.ts
  libraries/botframework-streaming/src/payloads/requestManager.ts
  libraries/botframework-streaming/src/payloads/sendOperations.ts
  libraries/botframework-streaming/src/payloads/streamManager.ts
  libraries/botframework-streaming/src/webSocket/browserWebSocket.ts
  libraries/botframework-streaming/src/webSocket/browserWebSocketClient.ts
  libraries/botframework-streaming/src/webSocket/factories/nodeWebSocketFactory.ts
  libraries/botframework-streaming/src/webSocket/factories/nodeWebSocketFactoryBase.ts
  libraries/botframework-streaming/src/webSocket/nodeWebSocket.ts
  libraries/botframework-streaming/src/webSocket/nodeWebSocketClient.ts
  libraries/botframework-streaming/src/webSocket/webSocketTransport.ts
Labels: Area: Docs

#2830 [#2602] [JSDoc] Add missing documentation for botbuilder-lg files
  .eslintrc.json
  libraries/botbuilder-lg/src/position.ts
  libraries/botbuilder-lg/src/range.ts
  libraries/botbuilder-lg/src/sourceRange.ts
  libraries/botbuilder-lg/src/staticChecker.ts
  libraries/botbuilder-lg/src/template.ts
  libraries/botbuilder-lg/src/templateException.ts
  libraries/botbuilder-lg/src/templateExtensions.ts
  libraries/botbuilder-lg/src/templateImport.ts
  libraries/botbuilder-lg/src/templates.ts
  libraries/botbuilder-lg/src/templatesParser.ts
Labels: Area: Docs

#2819 [#2602] [JSDoc] Add missing documentation for botbuilder
  libraries/botbuilder/src/eventFactory.ts
  libraries/botbuilder/src/fileTranscriptStore.ts
  libraries/botbuilder/src/handoffEventNames.ts
  libraries/botbuilder/src/inspectionMiddleware.ts
  libraries/botbuilder/src/statusCodeError.ts
  libraries/botbuilder/src/teamsActivityHandler.ts
  libraries/botbuilder/src/teamsActivityHelpers.ts
  libraries/botbuilder/src/teamsInfo.ts
Labels: Area: Docs

#2818 [#2602] [JSDoc] Add missing documentation for botbuilder/skills
  libraries/botbuilder/src/activityValidator.ts
  libraries/botbuilder/src/botFrameworkAdapter.ts
  libraries/botbuilder/src/botFrameworkHttpClient.ts
  libraries/botbuilder/src/channelServiceHandler.ts
  libraries/botbuilder/src/channelServiceRoutes.ts
  libraries/botbuilder/src/skills/skillHandler.ts
  libraries/botbuilder/src/skills/skillHttpClient.ts
  libraries/botbuilder/src/streaming/streamingHttpClient.ts
  libraries/botbuilder/src/streaming/tokenResolver.ts
Labels: Area: Docs

#2895 [PORT] DialogContextMemoryScope
  libraries/botbuilder-dialogs/src/memory/dialogStateManager.ts
  libraries/botbuilder-dialogs/src/memory/scopePath.ts
  libraries/botbuilder-dialogs/src/memory/scopes/dialogContextMemoryScope.ts
  libraries/botbuilder-dialogs/src/memory/scopes/index.ts
  libraries/botbuilder-dialogs/tests/memory_memoryScopes.test.js
Labels: Area: Adaptive

#2890 [PORT]Make language policy in MultiLanguageRecognizer align with the policy in UseLanguagePolicy
  libraries/botbuilder-dialogs-adaptive-testing/etc/botbuilder-dialogs-adaptive-testing.api.md
  libraries/botbuilder-dialogs-adaptive-testing/src/testScript.ts
  libraries/botbuilder-dialogs-adaptive-testing/tests/multiLanguageRecognizer.test.js
  libraries/botbuilder-dialogs-adaptive-testing/tests/resources/MultiLanguageRecognizerTests/MultiLanguageRecognizerTest_LanguagePolicy.test.dialog
  libraries/botbuilder-dialogs-adaptive/src/recognizers/multiLanguageRecognizer.ts
Labels: Area: Adaptive

#2922 [PORT]Ignore the null or empty result of the OutputFormat in TextInput
  libraries/botbuilder-dialogs-adaptive-testing/tests/resources/ActionTests/Action_TextInput.test.dialog
  libraries/botbuilder-dialogs-adaptive/src/input/textInput.ts
Labels: Area: Adaptive

#2235 Move QnAMaker/Luis components into botbuilder-ai
  libraries/botbuilder-ai-orchestrator/src/orchestratorAdaptiveRecognizer.ts
  libraries/botbuilder-ai/package.json
  libraries/botbuilder-ai/src/index.ts
  libraries/botbuilder-ai/src/luisAdaptiveRecognizer.ts
  libraries/botbuilder-ai/src/luisComponentRegistration.ts
  libraries/botbuilder-ai/src/qnaMakerComponentRegistration.ts
  libraries/botbuilder-ai/src/qnaMakerDialog.ts
  libraries/botbuilder-ai/src/qnaMakerRecognizer.ts
  libraries/botbuilder-ai/src/qnamaker-utils/bindToActivity.ts
  libraries/botbuilder-ai/tests/qna/QnaMaker_ReturnsAnswer.json
  libraries/botbuilder-ai/tests/qna/QnaMaker_ReturnsAnswerWithIntent.json
  libraries/botbuilder-ai/tests/qna/QnaMaker_ReturnsNoAnswer.json
  libraries/botbuilder-ai/tests/qna/QnaMaker_TopNAnswer.json
  libraries/botbuilder-ai/tests/qnaMakerDialog.test.js
  libraries/botbuilder-ai/tests/qnaMakerRecognizer.test.js
  libraries/botbuilder-dialogs-adaptive-testing/package.json
  libraries/botbuilder-dialogs-adaptive-testing/src/testRunner.ts
  libraries/botbuilder-dialogs-adaptive/package.json
  libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/logAction.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/sendActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/updateActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/adaptiveComponentRegistration.ts
  libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onQnAMatch.ts
  libraries/botbuilder-dialogs-adaptive/src/converters/activityTemplateConverter.ts
  libraries/botbuilder-dialogs-adaptive/src/converters/multiLanguageRecognizerConverter.ts
  libraries/botbuilder-dialogs-adaptive/src/converters/recognizerConverter.ts
  libraries/botbuilder-dialogs-adaptive/src/index.ts
  libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/luis/index.ts
  libraries/botbuilder-dialogs-adaptive/src/qnaMaker/index.ts
  libraries/botbuilder-dialogs-adaptive/src/recognizers/crossTrainedRecognizerSet.ts
  libraries/botbuilder-dialogs-adaptive/src/recognizers/index.ts
  libraries/botbuilder-dialogs-adaptive/src/recognizers/multiLanguageRecognizer.ts
  libraries/botbuilder-dialogs-adaptive/src/recognizers/recognizerSet.ts
  libraries/botbuilder-dialogs-adaptive/src/recognizers/regexRecognizer.ts
  libraries/botbuilder-dialogs-adaptive/src/recognizers/valueRecognizer.ts
  libraries/botbuilder-dialogs-adaptive/src/telemetryExtensions.ts
  libraries/botbuilder-dialogs-adaptive/src/templates/activityTemplate.ts
  libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts
  libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts
  libraries/botbuilder-dialogs-adaptive/tests/recognizer.test.js
  libraries/botbuilder-dialogs/src/dialogTurnStateConstants.ts
  libraries/botbuilder-dialogs/src/index.ts
  libraries/botbuilder-dialogs/src/recognizer.ts
  libraries/botbuilder-dialogs/src/template.ts
Labels: Area: Adaptive

#2929 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs-adaptive conditions folder 2/2
  libraries/botbuilder-dialogs-adaptive/src/conditions/onError.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onEventActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onHandoffActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onIntent.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onInvokeActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onMessageActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onMessageDeleteActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onMessageReactionActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onMessageUpdateActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onQnAMatch.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onRepromptDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/conditions/onTypingActivity.ts
Labels: Area: Docs

#2927 [#2602][JSDoc] Add missing documentation for botbuilder-dialogs-adaptive Actions folder 2/3
  libraries/botbuilder-dialogs-adaptive/src/actions/deleteProperties.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/deleteProperty.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/dynamicBeginDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/editActions.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/editArray.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/emitEvent.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/endDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/endTurn.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/forEach.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/forEachPage.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/getActivityMembers.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/getConversationMembers.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/gotoAction.ts
Labels: Area: Docs

#2917 [#2602] [JSDoc] Add missing documentation for botbuilder-dialogs-adaptive input folder
  libraries/botbuilder-dialogs-adaptive/src/input/ask.ts
  libraries/botbuilder-dialogs-adaptive/src/input/attachmentInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/choiceSet.ts
  libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/dateTimeInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/input/numberInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/oauthInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/textInput.ts
Labels: Area: Docs

#2925 [#2602][JSDoc] Add missing documentation for botbuilder-dialogs-adaptive Actions folder 1/3
  libraries/botbuilder-dialogs-adaptive/src/actions/actionScope.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/baseInvokeDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/beginDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/beginSkill.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/breakLoop.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/cancelAllDialogs.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/cancelAllDialogsBase.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/cancelDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/case.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/codeAction.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/continueLoop.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/deleteActivity.ts
Labels: Area: Docs

#2926 [#2602][JSDoc] Add missing documentation for botbuilder-dialogs-adaptive Actions folder 3/3
  libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/ifCondition.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/logAction.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/repeatDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/replaceDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/sendActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/setProperties.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/setProperty.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/signOutUser.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/switchCondition.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/telemetryTrackEventAction.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/traceActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/updateActivity.ts
Labels: Area: Docs
