Repository microsoft/botbuilder-js, pull requests merged in 2020-03, with the labels that each got.

#1845 Pass custom functions to imported .lg files
  libraries/botbuilder-lg/src/lgParser.ts
  libraries/botbuilder-lg/tests/lg.test.js
  libraries/botbuilder-lg/tests/testData/examples/CustomFunction.lg
  libraries/botbuilder-lg/tests/testData/examples/CustomFunctionSub.lg
Labels: adaptive, lg

#1849 Update LG template content range
  libraries/botbuilder-lg/src/LGFileLexer.g4
  libraries/botbuilder-lg/src/generated/LGFileLexer.ts
  libraries/botbuilder-lg/src/index.ts
  libraries/botbuilder-lg/src/lgFile.ts
  libraries/botbuilder-lg/src/lgTemplate.ts
  libraries/botbuilder-lg/src/mslgTool.ts
  libraries/botbuilder-lg/tests/lg.test.js
  libraries/botbuilder-lg/tests/testData/examples/2.lg
Labels: lg

#1861 Add tests for SkillDialog
  libraries/botbuilder-dialogs/src/skillDialog.ts
  libraries/botbuilder-dialogs/tests/skillDialog.test.js
Labels: Skills

#1894 Revert breaking changes around BotFrameworkClient implementations
  libraries/botbuilder-core/src/index.ts
  libraries/botbuilder-core/src/skills/botFrameworkClient.ts
  libraries/botbuilder-dialogs/src/dialogHelper.ts
  libraries/botbuilder/src/botFrameworkHttpClient.ts
  libraries/botbuilder/src/skills/skillHttpClient.ts
Labels: P0, R8, Skills

#1898 [master, cherry-pick] fix runDialog helper, fix callerId
  libraries/botbuilder-dialogs/src/dialogHelper.ts
  libraries/botbuilder-dialogs/tests/dialogHelper.test.js
  libraries/botbuilder/src/botFrameworkHttpClient.ts
Labels: Skills

#1889 trust reference.serviceUrl if credentials.appId is truthy
  libraries/botbuilder/src/botFrameworkAdapter.ts
  libraries/botbuilder/tests/botFrameworkAdapter.test.js
Labels: R9, blocked

#1910 update lg tsconfig and comments
  libraries/botbuilder-lg/src/staticChecker.ts
  libraries/botbuilder-lg/src/templateExtensions.ts
  libraries/botbuilder-lg/src/templateParser.ts
  libraries/botbuilder-lg/src/templates.ts
  libraries/botbuilder-lg/tsconfig.json
Labels: R9, lg
