Repository microsoft/botbuilder-js, pull requests merged in 2020-01, with the labels that each got.

#1531 fix comments and add get fullName method in fileResource
  libraries/botbuilder-ai/package-lock.json
  libraries/botbuilder-dialogs-declarative/src/factory/typeFactory.ts
  libraries/botbuilder-dialogs-declarative/src/pathUtil.ts
  libraries/botbuilder-dialogs-declarative/src/resources/fileResource.ts
  libraries/botbuilder-dialogs-declarative/src/resources/folderResoureProvider.ts
  libraries/botbuilder-dialogs-declarative/src/resources/resourceExplorer.ts
  samples/50. todo-bot/src/showToDos/index.ts
Labels: adaptive

#1575 remove "dom" from bf-streaming tsconfig and refactor code
  libraries/botframework-streaming/src/interfaces/IBrowserFileReader.ts
  libraries/botframework-streaming/src/interfaces/IBrowserWebSocket.ts
  libraries/botframework-streaming/src/interfaces/index.ts
  libraries/botframework-streaming/src/utilities/doesGlobalFileReaderExist.ts
  libraries/botframework-streaming/src/utilities/doesGlobalWebSocketExist.ts
  libraries/botframework-streaming/src/utilities/index.ts
  libraries/botframework-streaming/src/webSocket/browserWebSocket.ts
  libraries/botframework-streaming/src/webSocket/webSocketClient.ts
  libraries/botframework-streaming/tests/InternalUtilities.test.js
  libraries/botframework-streaming/tsconfig.json
Labels: P0

#1503 JS parity for multiLanguageGenerator in Adaptive
  libraries/botbuilder-dialogs-adaptive-tests/src/adaptiveComponentRegistration.ts
  libraries/botbuilder-dialogs-adaptive-tests/src/testing/testScript.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/httpRequest.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/logAction.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/sendActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/actions/updateActivity.ts
  libraries/botbuilder-dialogs-adaptive/src/activityProperty.ts
  libraries/botbuilder-dialogs-adaptive/src/generators/index.ts
  libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts
  libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGenerator.ts
  libraries/botbuilder-dialogs-adaptive/src/generators/multiLanguageGeneratorBase.ts
  libraries/botbuilder-dialogs-adaptive/src/generators/resourceMultiLanguageGenerator.ts
  libraries/botbuilder-dialogs-adaptive/src/generators/templateEngineLanguageGenerator.ts
  libraries/botbuilder-dialogs-adaptive/src/index.ts
  libraries/botbuilder-dialogs-adaptive/src/input/attachmentInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/choiceInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/confirmInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/datetimeInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/inputDialog.ts
  libraries/botbuilder-dialogs-adaptive/src/input/numberInput.ts
  libraries/botbuilder-dialogs-adaptive/src/input/textInput.ts
  libraries/botbuilder-dialogs-adaptive/src/languageGenerationMiddleware.ts
  libraries/botbuilder-dialogs-adaptive/src/languageGenerator.ts
  libraries/botbuilder-dialogs-adaptive/src/languagePolicy.ts
  libraries/botbuilder-dialogs-adaptive/src/multiLanguageResourceLoader.ts
  libraries/botbuilder-dialogs-adaptive/src/resources/fileResource.ts
  libraries/botbuilder-dialogs-adaptive/src/resources/fileResourceProvider.ts
  libraries/botbuilder-dialogs-adaptive/src/resources/folderResoureProvider.ts
  libraries/botbuilder-dialogs-adaptive/src/resources/index.ts
  libraries/botbuilder-dialogs-adaptive/src/resources/pathUtil.ts
  libraries/botbuilder-dialogs-adaptive/src/resources/resource.ts
  libraries/botbuilder-dialogs-adaptive/src/resources/resourceExplorer.ts
  libraries/botbuilder-dialogs-adaptive/src/resources/resourceProvider.ts
  libraries/botbuilder-dialogs-adaptive/src/stringTemplate.ts
  libraries/botbuilder-dialogs-adaptive/src/template.ts
  libraries/botbuilder-dialogs-adaptive/src/templates/activityTemplate.ts
  libraries/botbuilder-dialogs-adaptive/src/templates/index.ts
  libraries/botbuilder-dialogs-adaptive/src/templates/staticActivityTemplate.ts
  libraries/botbuilder-dialogs-adaptive/src/templates/textTemplate.ts
  libraries/botbuilder-dialogs-adaptive/tests/LGGenerator.test.js
  libraries/botbuilder-dialogs-adaptive/tests/adaptiveDialog.test.js
  libraries/botbuilder-dialogs-adaptive/tests/lg/test.de.lg
  libraries/botbuilder-dialogs-adaptive/tests/lg/test.en-GB.lg
  libraries/botbuilder-dialogs-adaptive/tests/lg/test.en-US.lg
  libraries/botbuilder-dialogs-adaptive/tests/lg/test.en.lg
  libraries/botbuilder-dialogs-adaptive/tests/lg/test.fr.lg
  libraries/botbuilder-dialogs-adaptive/tests/lg/test.lg
Labels: adaptive

#1586 [Skills] TrustServiceUrl from original conversationReference in SkillHandler
  libraries/botbuilder/src/skills/skillHandler.ts
  libraries/botbuilder/tests/skills/skillHandler.test.js
Labels: P0

#1613 [QoL] add declarationMap to tsconfig.json in libraries
  libraries/botbuilder-ai/tsconfig.json
  libraries/botbuilder-applicationinsights/tsconfig.json
  libraries/botbuilder-azure/tsconfig.json
  libraries/botbuilder-core/tsconfig.json
  libraries/botbuilder-dialogs/tsconfig.json
  libraries/botbuilder-lg/tsconfig.json
  libraries/botbuilder-testing/tsconfig.json
  libraries/botbuilder/tsconfig.json
  libraries/botframework-config/tsconfig.json
  libraries/botframework-connector/tsconfig.json
  libraries/botframework-expressions/tsconfig.json
  libraries/botframework-schema/tsconfig.json
  libraries/botframework-streaming/tsconfig.json
Labels: Quality of Life
